plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp'
    id 'com.google.dagger.hilt.android' version '2.60.1'
}

android {
    namespace 'com.tsutsen.platformplayer.core.data'
    compileSdk 37

    defaultConfig {
        minSdk 28
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlin {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
        }
    }
    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation project(':core:model')
    implementation project(':core:database')
    api project(':core:datastore')
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2"
    implementation 'androidx.media3:media3-exoplayer:1.9.0'
    implementation 'androidx.media3:media3-session:1.9.0'
    implementation 'androidx.media3:media3-exoplayer-dash:1.9.0'
    implementation 'androidx.media3:media3-exoplayer-hls:1.9.0'
    implementation 'androidx.media3:media3-datasource:1.9.0'
    
    // Hilt Dependency Injection
    implementation 'com.google.dagger:hilt-android:2.60.1'
    ksp 'com.google.dagger:hilt-android-compiler:2.60.1'
}
