package com.tsutsen.platformplayer.core.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color
import com.google.android.material.color.utilities.DynamicScheme
import com.google.android.material.color.utilities.Hct
import com.google.android.material.color.utilities.TonalPalette
import com.google.android.material.color.utilities.Variant
import com.tsutsen.platformplayer.core.datastore.model.PaletteStyle
import kotlin.math.min

/**
 * Theme engine — turns a few key colors into a full Material 3 theme pair.
 *
 * The user supplies [primary], and optionally [secondary]/[tertiary]; every
 * other role (40 of them, light and dark) is generated by the same
 * material-color-utilities pipeline PixelPlayer uses, so a custom theme is
 * as complete as a Material You one.
 *
 * Uses the API bundled in com.google.android.material:material (the app
 * already depends on it). Pure and allocation-cheap — results can be
 * remembered keyed by the inputs.
 */
object ThemeEngine {
    data class Schemes(
        val light: ColorScheme,
        val dark: ColorScheme,
    )

    /**
     * @param primary key color, ARGB (0xAARRGGBB)
     * @param secondary key color, ARGB, or null to derive from primary
     * @param tertiary key color, ARGB, or null to derive from secondary/primary
     */
    fun generate(
        primary: Int,
        secondary: Int?,
        tertiary: Int?,
        style: PaletteStyle,
    ): Schemes {
        val source = Hct.fromInt(primary)
        val secondaryColor = secondary ?: primary
        val tertiaryColor = tertiary ?: secondary ?: primary

        val primaryPalette = TonalPalette.fromInt(primary)
        val secondaryPalette = TonalPalette.fromInt(secondaryColor)
        val tertiaryPalette = TonalPalette.fromInt(tertiaryColor)
        // Neutrals keep the primary's hue; neutral is fully achromatic,
        // neutralVariant carries a little of the primary's chroma.
        val neutralPalette = TonalPalette.fromHueAndChroma(source.hue, 0.0)
        val neutralVariantPalette =
            TonalPalette.fromHueAndChroma(source.hue, min(source.chroma * 0.4, 12.0))

        val variant = variantFor(style)
        return Schemes(
            light =
                scheme(
                    source,
                    variant,
                    isDark = false,
                    primary,
                    secondaryColor,
                    tertiaryColor,
                    primaryPalette,
                    secondaryPalette,
                    tertiaryPalette,
                    neutralPalette,
                    neutralVariantPalette,
                ).toComposeColorScheme(),
            dark =
                scheme(
                    source,
                    variant,
                    isDark = true,
                    primary,
                    secondaryColor,
                    tertiaryColor,
                    primaryPalette,
                    secondaryPalette,
                    tertiaryPalette,
                    neutralPalette,
                    neutralVariantPalette,
                ).toComposeColorScheme(),
        )
    }

    private fun scheme(
        source: Hct,
        variant: Variant,
        isDark: Boolean,
        primary: Int,
        secondary: Int,
        tertiary: Int,
        primaryPalette: TonalPalette,
        secondaryPalette: TonalPalette,
        tertiaryPalette: TonalPalette,
        neutralPalette: TonalPalette,
        neutralVariantPalette: TonalPalette,
    ): DynamicScheme =
        DynamicScheme(
            source,
            variant,
            isDark,
            0.0,
            primaryPalette,
            secondaryPalette,
            tertiaryPalette,
            neutralPalette,
            neutralVariantPalette,
        )

    private fun variantFor(style: PaletteStyle): Variant =
        when (style) {
            PaletteStyle.TONAL_SPOT -> Variant.TONAL_SPOT
            PaletteStyle.VIBRANT -> Variant.VIBRANT
            PaletteStyle.EXPRESSIVE -> Variant.EXPRESSIVE
            PaletteStyle.FRUIT_SALAD -> Variant.FRUIT_SALAD
        }
}

private fun DynamicScheme.toComposeColorScheme(): ColorScheme =
    ColorScheme(
        primary = Color(getPrimary()),
        onPrimary = Color(getOnPrimary()),
        primaryContainer = Color(getPrimaryContainer()),
        onPrimaryContainer = Color(getOnPrimaryContainer()),
        inversePrimary = Color(getInversePrimary()),
        secondary = Color(getSecondary()),
        onSecondary = Color(getOnSecondary()),
        secondaryContainer = Color(getSecondaryContainer()),
        onSecondaryContainer = Color(getOnSecondaryContainer()),
        tertiary = Color(getTertiary()),
        onTertiary = Color(getOnTertiary()),
        tertiaryContainer = Color(getTertiaryContainer()),
        onTertiaryContainer = Color(getOnTertiaryContainer()),
        background = Color(getBackground()),
        onBackground = Color(getOnBackground()),
        surface = Color(getSurface()),
        onSurface = Color(getOnSurface()),
        surfaceVariant = Color(getSurfaceVariant()),
        onSurfaceVariant = Color(getOnSurfaceVariant()),
        surfaceTint = Color(getSurfaceTint()),
        inverseSurface = Color(getInverseSurface()),
        inverseOnSurface = Color(getInverseOnSurface()),
        error = Color(getError()),
        onError = Color(getOnError()),
        errorContainer = Color(getErrorContainer()),
        onErrorContainer = Color(getOnErrorContainer()),
        outline = Color(getOutline()),
        outlineVariant = Color(getOutlineVariant()),
        scrim = Color(getScrim()),
        surfaceBright = Color(getSurfaceBright()),
        surfaceDim = Color(getSurfaceDim()),
        surfaceContainer = Color(getSurfaceContainer()),
        surfaceContainerHigh = Color(getSurfaceContainerHigh()),
        surfaceContainerHighest = Color(getSurfaceContainerHighest()),
        surfaceContainerLow = Color(getSurfaceContainerLow()),
        surfaceContainerLowest = Color(getSurfaceContainerLowest()),
        primaryFixed = Color(getPrimaryFixed()),
        primaryFixedDim = Color(getPrimaryFixedDim()),
        onPrimaryFixed = Color(getOnPrimaryFixed()),
        onPrimaryFixedVariant = Color(getOnPrimaryFixedVariant()),
        secondaryFixed = Color(getSecondaryFixed()),
        secondaryFixedDim = Color(getSecondaryFixedDim()),
        onSecondaryFixed = Color(getOnSecondaryFixed()),
        onSecondaryFixedVariant = Color(getOnSecondaryFixedVariant()),
        tertiaryFixed = Color(getTertiaryFixed()),
        tertiaryFixedDim = Color(getTertiaryFixedDim()),
        onTertiaryFixed = Color(getOnTertiaryFixed()),
        onTertiaryFixedVariant = Color(getOnTertiaryFixedVariant()),
    )
