package com.tsutsen.platformplayer.core.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color
import com.google.android.material.color.utilities.DynamicScheme
import com.google.android.material.color.utilities.Hct
import com.google.android.material.color.utilities.MathUtils
import com.google.android.material.color.utilities.TonalPalette
import com.google.android.material.color.utilities.Variant
import com.tsutsen.platformplayer.core.datastore.model.PaletteStyle

/**
 * Theme engine — turns a few key colors into a full Material 3 theme pair.
 *
 * The user supplies [primary], and optionally [secondary]/[tertiary]; every
 * other role (40 of them, light and dark) is generated by the same
 * material-color-utilities pipeline PixelPlayer uses, so a custom theme is
 * as complete as a Material You one.
 *
 * Uses the API bundled in com.google.android.material:material (the app
 * already depends on it). Pure and allocation-cheap — results can be
 * remembered keyed by the inputs.
 */
object ThemeEngine {
    data class Schemes(
        val light: ColorScheme,
        val dark: ColorScheme,
    )

    /**
     * @param primary key color, ARGB (0xAARRGGBB)
     * @param secondary key color, ARGB, or null to derive from primary
     * @param tertiary key color, ARGB, or null to derive from secondary/primary
     */
    fun generate(
        primary: Int,
        secondary: Int?,
        tertiary: Int?,
        style: PaletteStyle,
    ): Schemes {
        val palettes = buildPalettes(primary, secondary, tertiary, style)
        val source = Hct.fromInt(primary)

        // The material 1.13.0-bundled DynamicScheme ignores `variant` when
        // given explicit palettes (its role tones are variant-agnostic), so
        // the style's behavior lives in [buildPalettes], not here.
        val variant = variantFor(style)
        return Schemes(
            light =
                DynamicScheme(
                    source,
                    variant,
                    false,
                    0.0,
                    palettes.primary,
                    palettes.secondary,
                    palettes.tertiary,
                    palettes.neutral,
                    palettes.neutralVariant,
                ).toComposeColorScheme(),
            dark =
                DynamicScheme(
                    source,
                    variant,
                    true,
                    0.0,
                    palettes.primary,
                    palettes.secondary,
                    palettes.tertiary,
                    palettes.neutral,
                    palettes.neutralVariant,
                ).toComposeColorScheme(),
        )
    }

    /**
     * Per-style tonal palette construction, following the material-
     * color-utilities 2021 spec.
     *
     * The user's picked colors are always respected verbatim ([TonalPalette.
     * fromInt]); the style only decides how the *unpicked* palettes
     * (secondary, tertiary, neutral, neutralVariant) are derived from the
     * primary. This is what makes the four styles visually distinct.
     */
    private data class Palettes(
        val primary: TonalPalette,
        val secondary: TonalPalette,
        val tertiary: TonalPalette,
        val neutral: TonalPalette,
        val neutralVariant: TonalPalette,
    )

    private fun buildPalettes(
        primary: Int,
        secondary: Int?,
        tertiary: Int?,
        style: PaletteStyle,
    ): Palettes {
        val source = Hct.fromInt(primary)
        val hue = source.hue
        val picked = { argb: Int? -> argb?.let { TonalPalette.fromInt(it) } }

        val secondaryTonal =
            when (style) {
                PaletteStyle.TONAL_SPOT -> TonalPalette.fromHueAndChroma(hue, 16.0)
                PaletteStyle.VIBRANT ->
                    TonalPalette.fromHueAndChroma(
                        DynamicScheme.getRotatedHue(
                            source,
                            doubleArrayOf(0.0, 41.0, 61.0, 101.0, 131.0, 181.0, 251.0, 301.0, 360.0),
                            doubleArrayOf(18.0, 15.0, 10.0, 12.0, 15.0, 18.0, 15.0, 12.0, 12.0),
                        ),
                        24.0,
                    )
                PaletteStyle.EXPRESSIVE ->
                    TonalPalette.fromHueAndChroma(
                        DynamicScheme.getRotatedHue(
                            source,
                            doubleArrayOf(0.0, 21.0, 51.0, 121.0, 151.0, 191.0, 271.0, 321.0, 360.0),
                            doubleArrayOf(45.0, 95.0, 45.0, 20.0, 45.0, 90.0, 45.0, 45.0, 45.0),
                        ),
                        24.0,
                    )
                PaletteStyle.FRUIT_SALAD ->
                    TonalPalette.fromHueAndChroma(MathUtils.sanitizeDegreesDouble(hue - 50.0), 36.0)
            }

        val tertiaryTonal =
            when (style) {
                PaletteStyle.TONAL_SPOT ->
                    TonalPalette.fromHueAndChroma(MathUtils.sanitizeDegreesDouble(hue + 60.0), 24.0)
                PaletteStyle.VIBRANT ->
                    TonalPalette.fromHueAndChroma(
                        DynamicScheme.getRotatedHue(
                            source,
                            doubleArrayOf(0.0, 41.0, 61.0, 101.0, 131.0, 181.0, 251.0, 301.0, 360.0),
                            doubleArrayOf(35.0, 30.0, 20.0, 25.0, 30.0, 35.0, 30.0, 25.0, 25.0),
                        ),
                        32.0,
                    )
                PaletteStyle.EXPRESSIVE ->
                    TonalPalette.fromHueAndChroma(
                        DynamicScheme.getRotatedHue(
                            source,
                            doubleArrayOf(0.0, 21.0, 51.0, 121.0, 151.0, 191.0, 271.0, 321.0, 360.0),
                            doubleArrayOf(120.0, 120.0, 20.0, 45.0, 20.0, 15.0, 20.0, 120.0, 120.0),
                        ),
                        32.0,
                    )
                PaletteStyle.FRUIT_SALAD -> TonalPalette.fromHueAndChroma(hue, 36.0)
            }

        val neutralChroma: Double
        val neutralVariantChroma: Double
        val neutralHueShift: Double
        when (style) {
            PaletteStyle.TONAL_SPOT -> {
                neutralChroma = 6.0; neutralVariantChroma = 8.0; neutralHueShift = 0.0
            }
            PaletteStyle.VIBRANT -> {
                neutralChroma = 10.0; neutralVariantChroma = 12.0; neutralHueShift = 0.0
            }
            PaletteStyle.EXPRESSIVE -> {
                neutralChroma = 8.0; neutralVariantChroma = 12.0; neutralHueShift = 15.0
            }
            PaletteStyle.FRUIT_SALAD -> {
                neutralChroma = 10.0; neutralVariantChroma = 16.0; neutralHueShift = 0.0
            }
        }
        val neutralHue = MathUtils.sanitizeDegreesDouble(hue + neutralHueShift)

        return Palettes(
            primary = TonalPalette.fromInt(primary),
            secondary = picked(secondary) ?: secondaryTonal,
            tertiary = picked(tertiary) ?: tertiaryTonal,
            neutral = TonalPalette.fromHueAndChroma(neutralHue, neutralChroma),
            neutralVariant = TonalPalette.fromHueAndChroma(neutralHue, neutralVariantChroma),
        )
    }

    private fun variantFor(style: PaletteStyle): Variant =
        when (style) {
            PaletteStyle.TONAL_SPOT -> Variant.TONAL_SPOT
            PaletteStyle.VIBRANT -> Variant.VIBRANT
            PaletteStyle.EXPRESSIVE -> Variant.EXPRESSIVE
            PaletteStyle.FRUIT_SALAD -> Variant.FRUIT_SALAD
        }
}

private fun DynamicScheme.toComposeColorScheme(): ColorScheme =
    ColorScheme(
        primary = Color(getPrimary()),
        onPrimary = Color(getOnPrimary()),
        primaryContainer = Color(getPrimaryContainer()),
        onPrimaryContainer = Color(getOnPrimaryContainer()),
        inversePrimary = Color(getInversePrimary()),
        secondary = Color(getSecondary()),
        onSecondary = Color(getOnSecondary()),
        secondaryContainer = Color(getSecondaryContainer()),
        onSecondaryContainer = Color(getOnSecondaryContainer()),
        tertiary = Color(getTertiary()),
        onTertiary = Color(getOnTertiary()),
        tertiaryContainer = Color(getTertiaryContainer()),
        onTertiaryContainer = Color(getOnTertiaryContainer()),
        background = Color(getBackground()),
        onBackground = Color(getOnBackground()),
        surface = Color(getSurface()),
        onSurface = Color(getOnSurface()),
        surfaceVariant = Color(getSurfaceVariant()),
        onSurfaceVariant = Color(getOnSurfaceVariant()),
        surfaceTint = Color(getSurfaceTint()),
        inverseSurface = Color(getInverseSurface()),
        inverseOnSurface = Color(getInverseOnSurface()),
        error = Color(getError()),
        onError = Color(getOnError()),
        errorContainer = Color(getErrorContainer()),
        onErrorContainer = Color(getOnErrorContainer()),
        outline = Color(getOutline()),
        outlineVariant = Color(getOutlineVariant()),
        scrim = Color(getScrim()),
        surfaceBright = Color(getSurfaceBright()),
        surfaceDim = Color(getSurfaceDim()),
        surfaceContainer = Color(getSurfaceContainer()),
        surfaceContainerHigh = Color(getSurfaceContainerHigh()),
        surfaceContainerHighest = Color(getSurfaceContainerHighest()),
        surfaceContainerLow = Color(getSurfaceContainerLow()),
        surfaceContainerLowest = Color(getSurfaceContainerLowest()),
        primaryFixed = Color(getPrimaryFixed()),
        primaryFixedDim = Color(getPrimaryFixedDim()),
        onPrimaryFixed = Color(getOnPrimaryFixed()),
        onPrimaryFixedVariant = Color(getOnPrimaryFixedVariant()),
        secondaryFixed = Color(getSecondaryFixed()),
        secondaryFixedDim = Color(getSecondaryFixedDim()),
        onSecondaryFixed = Color(getOnSecondaryFixed()),
        onSecondaryFixedVariant = Color(getOnSecondaryFixedVariant()),
        tertiaryFixed = Color(getTertiaryFixed()),
        tertiaryFixedDim = Color(getTertiaryFixedDim()),
        onTertiaryFixed = Color(getOnTertiaryFixed()),
        onTertiaryFixedVariant = Color(getOnTertiaryFixedVariant()),
    )
