package com.tsutsen.platformplayer.core.data.service

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Intent
import androidx.core.app.NotificationCompat
import androidx.media3.exoplayer.ExoPlayer
import androidx.media3.session.MediaSession
import androidx.media3.session.MediaSessionService
import com.tsutsen.platformplayer.core.data.R
import com.tsutsen.platformplayer.core.data.repository.PlayerRepository
import dagger.hilt.android.AndroidEntryPoint
import javax.inject.Inject
import java.util.UUID

/**
 * Registers playback with the system: media notification, lock-screen
 * controls, media buttons and the quick-settings media tile.
 *
 * The notification is generated by media3 from the player's current
 * MediaItem metadata (title / artist / artwork) and playback state.
 * Started by PlayerRepositoryImpl once the ExoPlayer is playing.
 */
@AndroidEntryPoint
class PlayerService : MediaSessionService() {

    @Inject
    lateinit var playerRepository: PlayerRepository

    private var session: MediaSession? = null
    private var sessionPlayer: ExoPlayer? = null
    private var fallbackPlayer: ExoPlayer? = null
    private var placeholderShown = false

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        val result = super.onStartCommand(intent, flags, startId)
        if (intent == null) {
            // Restart after process death — the in-process player is gone,
            // there is nothing to play.
            stopSelf()
            return result
        }
        // Satisfy the 5-second foreground-service deadline immediately.
        // media3's MediaNotificationManager only promotes the service to
        // foreground once the session's player timeline is non-empty
        // (see MediaNotificationManager#shouldShowNotification), and a
        // manifest fetch can take longer than 5 seconds — otherwise the
        // system kills the process with
        // ForegroundServiceDidNotStartInTimeException. The real media
        // notification replaces this placeholder (same notification id).
        if (!placeholderShown) {
            startForeground(NOTIFICATION_ID, placeholderNotification())
            placeholderShown = true
        }
        return result
    }

    override fun onGetSession(controllerInfo: MediaSession.ControllerInfo): MediaSession {
        val cached = session
        // The service is only started once the ExoPlayer exists; the
        // fallback covers a stray bind after the player was released.
        val player = playerRepository.exoPlayer ?: ExoPlayer.Builder(this).build().also { fallbackPlayer = it }
        if (cached != null && sessionPlayer !== player) {
            // A new playback created a new ExoPlayer — the cached session
            // is bound to the old (released) player, so replace it.
            removeSession(cached)
            cached.release()
            session = null
        }
        var current = session
        if (current == null) {
            // Open the app's main activity (launcher intent avoids a
            // dependency on the app module from core:data).
            val openApp =
                PendingIntent
                    .getActivity(
                        this,
                        0,
                        Intent(Intent.ACTION_MAIN)
                            .addCategory(Intent.CATEGORY_LAUNCHER)
                            .setPackage(packageName),
                        PendingIntent.FLAG_IMMUTABLE,
                    )
            // Unique id: media3 registers session ids in a process-wide
            // map and the default (empty) id collides across service
            // instances, making every second playback fail to connect.
            current =
                MediaSession
                    .Builder(this, player)
                    .setId(UUID.randomUUID().toString())
                    .setSessionActivity(openApp)
                    .build()
            session = current
            sessionPlayer = player
            addSession(current)
        }
        return current
    }

    override fun onDestroy() {
        if (placeholderShown) {
            stopForeground(STOP_FOREGROUND_REMOVE)
            placeholderShown = false
        }
        // MediaSessionService.onDestroy does not release sessions; without
        // this the session id stays registered in media3's process-wide
        // map and the next session with the same id cannot be built.
        session?.release()
        session = null
        sessionPlayer = null
        fallbackPlayer?.release()
        fallbackPlayer = null
        super.onDestroy()
    }

    private fun placeholderNotification(): Notification {
        val channelId = "bluejay_playback_placeholder"
        val notificationManager = getSystemService(NotificationManager::class.java)
        if (notificationManager.getNotificationChannel(channelId) == null) {
            notificationManager.createNotificationChannel(
                NotificationChannel(channelId, "Playback", NotificationManager.IMPORTANCE_LOW),
            )
        }
        val openApp =
            PendingIntent
                .getActivity(
                    this,
                    0,
                    Intent(Intent.ACTION_MAIN)
                        .addCategory(Intent.CATEGORY_LAUNCHER)
                        .setPackage(packageName),
                    PendingIntent.FLAG_IMMUTABLE,
                )
        return NotificationCompat
            .Builder(this, channelId)
            .setSmallIcon(R.drawable.ic_play_notif)
            .setContentTitle("Bluejay")
            .setCategory(Notification.CATEGORY_TRANSPORT)
            .setOngoing(true)
            .setContentIntent(openApp)
            .build()
    }

    companion object {
        // Must match media3's DefaultMediaNotificationProvider.DEFAULT_NOTIFICATION_ID
        // so the real media notification replaces this placeholder instead
        // of appearing alongside it.
        private const val NOTIFICATION_ID = 1001
    }
}
