package com.tsutsen.platformplayer.core.data.service

import android.app.PendingIntent
import android.content.Intent
import androidx.media3.common.MediaItem
import androidx.media3.common.MediaMetadata
import androidx.media3.exoplayer.ExoPlayer
import androidx.media3.session.MediaSession
import androidx.media3.session.MediaSessionService
import com.tsutsen.platformplayer.core.data.repository.PlayerRepository
import dagger.hilt.android.AndroidEntryPoint
import javax.inject.Inject

/**
 * Registers playback with the system: media notification, lock-screen
 * controls, media buttons and the quick-settings media tile.
 *
 * The notification is generated by media3 from the player's current
 * [MediaItem] metadata (title / artist / artwork) and playback state.
 * Started by PlayerRepositoryImpl once the ExoPlayer is playing.
 */
@AndroidEntryPoint
class PlayerService : MediaSessionService() {

    @Inject
    lateinit var playerRepository: PlayerRepository

    private var session: MediaSession? = null
    private var fallbackPlayer: ExoPlayer? = null

    override fun onGetSession(controllerInfo: MediaSession.ControllerInfo): MediaSession {
        var existing = session
        if (existing == null) {
            // The service is only started once the ExoPlayer exists; the
            // fallback covers a stray bind after the player was released.
            val player = playerRepository.exoPlayer ?: ExoPlayer.Builder(this).build().also { fallbackPlayer = it }
            // Open the app's main activity (launcher intent avoids a
            // dependency on the app module from core:data).
            val openApp =
                PendingIntent
                    .getActivity(
                        this,
                        0,
                        Intent(Intent.ACTION_MAIN)
                            .addCategory(Intent.CATEGORY_LAUNCHER)
                            .setPackage(packageName),
                        PendingIntent.FLAG_IMMUTABLE,
                    )
            existing =
                MediaSession
                    .Builder(this, player)
                    .setSessionActivity(openApp)
                    .build()
            session = existing
            addSession(existing)
        }
        return existing
    }

    override fun onDestroy() {
        fallbackPlayer?.release()
        super.onDestroy()
    }
}
