plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose' version '2.4.0'
    id 'com.google.dagger.hilt.android' version '2.60.1'
    id 'com.google.devtools.ksp'
}

android {
    namespace 'com.tsutsen.platformplayer.feature.search.impl'
    compileSdk 37

    defaultConfig {
        minSdk 28
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlin {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
        }
    }

    buildFeatures {
        compose true
    }
}

dependencies {
    implementation project(':core:designsystem')
    implementation project(':core:data')
    implementation project(':feature:library:impl')
    implementation project(':feature:player:impl')
    implementation project(':core:navigation')
    implementation project(':core:model')
    implementation project(':core:ui')
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation platform('androidx.compose:compose-bom:2026.05.01')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.foundation:foundation'
    implementation 'androidx.compose.runtime:runtime'
    implementation 'androidx.compose.material3:material3:1.5.0-alpha27'
    implementation 'androidx.compose.material:material-icons-extended'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose'
    implementation 'androidx.activity:activity-compose:1.13.0'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2"

    //Hilt Dependency Injection
    implementation 'com.google.dagger:hilt-android:2.60.1'
    ksp 'com.google.dagger:hilt-android-compiler:2.60.1'
    implementation 'androidx.hilt:hilt-navigation-compose:1.2.0'
}
