plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android' version '2.2.21'
}

android {
    namespace 'com.futo.platformplayer.core.datastore'
    compileSdk 36

    defaultConfig {
        minSdk 28
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation project(':core:model')
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.datastore:datastore-preferences:1.1.1'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2"
}
