plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android' version '2.2.21'
    id 'org.jetbrains.kotlin.plugin.compose' version '2.2.21'
    id 'com.google.dagger.hilt.android'
    id 'com.google.devtools.ksp'
}

android {
    namespace 'com.tsutsen.platformplayer.feature.settings.impl'
    compileSdk 36

    defaultConfig {
        minSdk 28
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        compose true
    }
}

dependencies {
    implementation project(':core:designsystem')
    implementation project(':core:data')
    implementation project(':core:navigation')
    implementation project(':core:model')
    implementation project(':core:ui')
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation platform('androidx.compose:compose-bom:2026.05.01')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.animation:animation'
    implementation 'androidx.compose.foundation:foundation'
    implementation 'androidx.compose.foundation:foundation-layout'
    implementation 'androidx.compose.runtime:runtime'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.material:material-icons-extended'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose'
    implementation 'androidx.activity:activity-compose'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2"
    
    // Hilt
    implementation "com.google.dagger:hilt-android:2.58"
    ksp "com.google.dagger:hilt-compiler:2.58"
    implementation 'androidx.hilt:hilt-navigation-compose:1.2.0'
}
